# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  20210115aspcore:
    image: 20210115aspcore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000
